### ISSUE TITLE
Node.js 12 action is deprecated

### ISSUE THREAD

**Issue by bynnchapu** [e1himself/goss-installation-action#16]
I found following annotation message on GitHub Actions when I use this Action.

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: e1himself/goss-installation-action
```

It seems Node.js 12 action is deprecated.
So we need to take update to Node.js 16 environment.

Finally, this action is useful for me.  Thank you for publishing this action.

**Comment by e1himself** [comment]
@bynnchapu this should have been addressed in the latest release. Please give it a try and confirm it's good now.

Thanks for reporting it! :+1:
