### ISSUE TITLE
Goss new org and version

### ISSUE THREAD

**Issue by onedr0p** [e1himself/goss-installation-action#21]
Goss has moved to a new home https://github.com/goss-org/goss and has a newer version.

**Comment by e1himself** [comment]
Hey @onedr0p!

I've spent time upgrading the code and all its dependencies. Including updating the goss release binaries paths.

As long as you have been using `e1himself/goss-installation-action@v1`, you don't have to change anything to get the latest action in your workflow.

Please check if it works to confirm it's all good. 

I'm looking forward to hearing back from you.

Thanks! :raised_hands:

**Comment by onedr0p** [comment]
I'll try to get back to you on this but it's the holidays, you'll definitely hear from me if something is broken 😆 
Thanks again and happy holidays!
